title = "Hora configuration"

[webui]
    port = "8080"
[prediction]
	interval = "1m"
	leadtime = "10m"
	precision = "1ns"
[adm]
    [adm.fileio]
        enabled = false
        path = "/tmp/adm.json"
    [adm.netio]
        enabled = true
[cfp]
    [cfp.responsetime]
	    unit = "1ns"
	    threshold = "100ms"
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
	[cfp.errorrate]
    [cfp.cpu]
        threshold = 1000
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
    [cfp.memory]
      	threshold = 2000000000
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
[fpm]
    updateinterval = "10ms"
[rserve]
    hostname = "rserve"
	port = 6311
[influxdb]
    addr = "http://influxdb:8086"
	username = "root"
	password = "root"
	batch = false
	[influxdb.db]
	    k8s = "k8s"
	    kieker = "kieker"
		hora = "hora"
	[influxdb.table]
		k8s = "k8s"
	    kieker = "operation_execution"
		hora = "hora"
