title = "Hora configuration"

[prediction]
	interval = "1m"
	leadtime = "10m"
	precision = "1ns"
[adm]
    [adm.filewatcher]
        enabled = false
        path = "/tmp/adm.json"
    [adm.restapi]
        enabled = true
		port = "8080"
[cfp]
    [cfp.responsetime]
	    unit = "1ns"
	    threshold = "100ms"
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
	[cfp.errorrate]
    [cfp.cpu]
        threshold = 1000
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
    [cfp.memory]
      	threshold = 2000000000
		predictor = "arima"
        history = "20m"
		aggregation = "percentile"
		aggregationvalue = 95
[fpm]
    updateinterval = "10ms"
[rserve]
    hostname = "rserve"
	port = 6311
[influxdb]
	batch = false
    [influxdb.kieker]
        addr = "http://influxdb:8086"
	    username = "root"
	    password = "root"
	    db = "kieker"
    [influxdb.k8s]
        addr = "http://influxdb:8086"
	    username = "root"
	    password = "root"
	    db = "kieker"
    [influxdb.hora]
	    addr = "http://influxdb:8086"
        username = "root"
	    password = "root"
	    db = "hora"
