apiVersion: v1
kind: Service
metadata:
  name: hora
  labels:
    name: hora
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 31100
  selector:
    name: hora
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hora
  labels:
    name: hora
spec:
  replicas: 1
  selector:
    name: hora
  template:
    metadata:
      labels:
        name: hora
    spec:
      containers:
      - name: hora
        image: teeratpitakrat/hora:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
